### PR TITLE
qatdeviceplugin_webhook: Extract only relevant parts for the validation

### LINKED ISSUE #605: image name validation fails when registry hostname:port is specified
the validation of a valid image entry fails:
`localhost:8080/intel-sgx-plugin:1.2.3`

### PR DESCRIPTION
**Pull request by ozhuraki**
Since we currently validate only the image name and the tag,
ignore registry, vendor and extract only relevant parts.

Closes #605

### CODE REVIEW

File: pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go [hunk 1]
```diff
@@ -88,17 +89,18 @@ func (r *QatDevicePlugin) ValidateDelete() error {
 }
 
 func (r *QatDevicePlugin) validatePlugin() error {
-	parts := strings.SplitN(r.Spec.Image, ":", 2)
```
Comment (mythi) [inline pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go:91]:
```suggestion
return validatePluginImage(r.Spec.Image, "intel-qat-plugin", qatMinVersion)
```

we could just return the output from `validatePluginImage` (see, e.g., dsadeviceplugin_webhook.go)

**Review by mythi — CHANGES_REQUESTED** [review]

File: pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go (hunk 1 above)
Comment (ozhuraki) [reply pkg/apis/deviceplugin/v1/qatdeviceplugin_webhook.go:91]: Thanks for the input. Done. Please take a look.

**Review by mythi — APPROVED** [review]
thanks!

**Review by rojkov — APPROVED** [review]
